feat(unlock-app) - Settings page hooks
unlock-protocol/unlock pull request #10329
Opened 2022-11-21 12:39 UTC by kalidiagne

# Description

**Form validation** 
<img width="700" alt="Screenshot 2022-11-21 at 13 02 50" src="https://user-images.githubusercontent.com/20865711/203057155-a4dc930e-94a7-4112-9f72-a9e88f8b29df.png">

<img width="700" alt="Screenshot 2022-11-21 at 13 38 15" src="https://user-images.githubusercontent.com/20865711/203057253-4d160964-3eaf-4c11-bf4b-ffe645ec8f34.png">

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2022-11-21 13:45 UTC, julien51 commented
@kalidiagne I think it would be good to use a toggle above the field to let the user decide to not use a specific hook and in that case, use the `0x0` value for that one.

2022-11-21 13:46 UTC, julien51 requested changes
Looks good but for simplicity use a toggle above the field (similar to how we do `unlimnited` or `free`).

2022-11-23 12:34 UTC, kalidiagne commented
> Looks good but for simplicity use a toggle above the field (similar to how we do `unlimnited` or `free`).
<img width="715" alt="Screenshot 2022-11-23 at 13 23 42" src="https://user-images.githubusercontent.com/20865711/203548071-22f96a28-48cf-4344-8b02-484eb41beb3c.png">

<img width="838" alt="Screenshot 2022-11-23 at 11 05 56" src="https://user-images.githubusercontent.com/20865711/203548091-0173814c-8b9a-4ddc-a4ed-b48fdf9612dd.png">

2022-11-23 14:11 UTC, julien51 commented on packages/unlock-js/src/PublicLock/v12/setEventHooks.js
> +    keyPurchase = '',
The default value should be the Zero address

2022-11-23 15:34 UTC, julien51 approved these changes
LGTM!

2022-11-23 16:54 UTC, merged