Update schema.graphql
unlock-protocol/unlock pull request #10525
Opened 2022-12-06 22:18 UTC by PaulieB14

Added descriptions to Schema

# Description

# Issues

Fixes #
Refs #

# Checklist:

- [x ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have updated the docs to reflect my changes if applicable
- [ x] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ x] I have performed a self-review of my own code
- [ x] If my code involves visual changes, I am adding applicable screenshots to this thread

<!--

2022-12-06 23:21 UTC, julien51 commented
Ho @PaulieB14 This is _very_ cool! Please open another PR and add yourself to the CLA file so we can approve that one!

2022-12-06 23:21 UTC, julien51 commented
It needs to be in _another_ PR :/

2022-12-06 23:22 UTC, julien51 commented on CLA.txt
> +PauliB14
ha no that's in this file: https://github.com/unlock-protocol/unlock/blob/master/.clabot

2022-12-06 23:22 UTC, julien51 commented on subgraph/schema.graphql
> +  "Transaction hash"
```suggestion
  "Unique ID for the Lock object (uses the lock address)"
```

2022-12-06 23:22 UTC, julien51 commented on subgraph/schema.graphql
> +  "Gets the token symbol"
```suggestion
  "Token symbol" 
```

2022-12-06 23:23 UTC, julien51 commented on subgraph/schema.graphql
> +  "Price of the lock"
```suggestion
  "Price of the keys sold by the lock" 
```

2022-12-06 23:24 UTC, julien51 commented on subgraph/schema.graphql
> +  "Number of keys owned by keyOwner (expired or not)"
```suggestion
  "Number of keys minted (expired or not)"
```

2022-12-06 23:24 UTC, julien51 commented on subgraph/schema.graphql
> +  "Setting for the max number of keys"
```suggestion
  "Maximum number of keys for sale" 
```

2022-12-06 23:24 UTC, julien51 commented on subgraph/schema.graphql
> +  "The block the last key was minted"
```suggestion
  "The timestamp of the block in which the last key was minted"
```

2022-12-06 23:25 UTC, julien51 commented on subgraph/schema.graphql
> +  "Transaction hash"
```suggestion
  "Unique identifier for a key (combination of lock address and token id)" 
```

2022-12-06 23:25 UTC, julien51 commented on subgraph/schema.graphql
> +  "TokenId for a given user"
```suggestion
  "TokenId for a given key" 
```

2022-12-06 23:25 UTC, julien51 commented on subgraph/schema.graphql
> +  "An assigned title set on an Unlock key which gives a specific wallet address authorization to transfer, share or cancel"
```suggestion
  "Address of the key owner"
```

2022-12-06 23:26 UTC, julien51 commented on subgraph/schema.graphql
> +  "Transaction hash"
```suggestion
  "Day identifier" 
```

2022-12-06 23:26 UTC, julien51 commented on subgraph/schema.graphql
> +  "Create lock This deploys a lock for a creator. It also keeps track of the deployed lock"
```suggestion
  "Number of locks deployed on that dat"
```

2022-12-07 02:39 UTC, wonderwomancode requested changes
Few minor edits :-)

2022-12-07 02:39 UTC, wonderwomancode commented on subgraph/schema.graphql
> +  "Invoked by a Lock manager to expire the user's key and perform a refund and cancellation of the keyThrows"
"keyThrows" should be "key"

2022-12-07 02:39 UTC, wonderwomancode commented on subgraph/schema.graphql
> +  "Total value exchanged in the network"
"in" should be "on"

2022-12-07 17:46 UTC, julien51 commented on subgraph/schema.graphql
> + "The maximum number of key allowed for a single address"
```suggestion
 "The maximum number of keys allowed for a single address"
```

2022-12-08 15:23 UTC, merged