feat(unlock-protocol-com) - use footer component
unlock-protocol/unlock pull request #10574
Opened 2022-12-13 14:11 UTC by kalidiagne

# Description

Replace the footer component.

### Desktop
<img width="1718" alt="Screenshot 2022-12-13 at 15 06 57" src="https://user-images.githubusercontent.com/20865711/207355602-8f143f79-0049-451c-9aa9-25e1ad3c0ce6.png">

### Mobile
<img width="430" alt="Screenshot 2022-12-13 at 15 07 43" src="https://user-images.githubusercontent.com/20865711/207355611-6a9492fe-ead6-4966-a2ec-87e62de09526.png">

### Demo
https://user-images.githubusercontent.com/20865711/207355900-b2e57f58-965e-46a8-a139-ee573634a103.mov

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2022-12-13 14:26 UTC, julien51 commented on unlock-protocol-com/src/components/layout/DefaultLayout.tsx
> +        url: 'https://staging-app.unlock-protocol.com/locks',
Not right! Please use env vars here to distinguish links between staging and prod

2022-12-13 14:27 UTC, julien51 requested changes
Link to the app is not correct :)

2022-12-13 14:27 UTC, julien51 commented on unlock-protocol-com/src/components/interface/Footer/index.tsx
> -      href: `${unlockConfig.appURL!}/locks`,
See here @kalidiagne

2022-12-13 15:16 UTC, kalidiagne commented
need https://github.com/unlock-protocol/unlock/pull/10575 before merge!

2022-12-14 09:54 UTC, kalidiagne commented
> need #10575 before merge!

merged!

2022-12-14 11:28 UTC, kalidiagne commented
> julien51

done

2022-12-14 13:50 UTC, julien51 approved these changes

2022-12-14 15:20 UTC, merged