feat(locksmith) - receipts controllers
unlock-protocol/unlock pull request #10764
Opened 2023-01-17 12:07 UTC by kalidiagne

# Description

- [x] add `receiptsController`/`receiptsBaseController`
- [x] add `save`/`get` functions to retrieve and get receipts for specific controllers 
- [x] add `lockAddress`, `network` and `hash` attributes to models  

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2023-01-17 14:37 UTC, julien51 commented on locksmith/src/models/receiptsBase.ts
> +  declare lockAddress: string
We may not need the lockAdress because we can look up by transaction but I think it;s ok!

2023-01-17 14:38 UTC, julien51 commented on locksmith/src/controllers/v2/receiptsBaseController.ts
> +      if (!supplier.length) {
For now let's make all the fields as optional please.

2023-01-17 14:39 UTC, julien51 requested changes
Can we please use zod to stay consistent with the rest of the application?

2023-01-18 15:09 UTC, kalidiagne commented on locksmith/src/models/receiptsBase.ts
> +  declare hash: string
@julien51  can we use only `lockAddress` here to get supplier details?

2023-01-19 16:55 UTC, julien51 commented on locksmith/src/controllers/v2/receiptBaseController.ts
> +          const [{ dataValues }] = await ReceiptBase.upsert(
If you use `upsert` there is no need to distinguish the 2 cases because `upsert` means update OR insert

2023-01-19 16:57 UTC, julien51 requested changes
Please refactor. Since you are using `upsert` there is no need to check if the objects exist first.
So either you keep `upsert` and then remove the `create` logic, or change `upsert` in `update`

2023-01-19 18:08 UTC, julien51 approved these changes
much cleaner!

2023-01-20 08:45 UTC, merged