feat(subgraph) - Add more details for receipts
unlock-protocol/unlock pull request #10825
Opened 2023-01-27 11:26 UTC by kalidiagne

# Description
We need `keyId` and `owner` for receipts to be able to get all receipts for a specific `keyId` of an owner 

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2023-01-27 12:31 UTC, clemsos commented on subgraph/src/public-lock.ts
> +    createReceipt(event, Address.fromString(''), event.params.tokenId)
not sure when you end up with an empty key owner on renewal? Also this `Address.fromString('')` gives a null address?

2023-01-27 12:32 UTC, clemsos commented on subgraph/src/public-lock.ts
> +    createReceipt(event, Bytes.empty(), tokenId.value)
Same as above, when does a key without an owner happen in renewal? We should not pass empty Bytes but at least a null address

2023-01-27 12:33 UTC, clemsos reviewed
Seems weird to store an empty key owner in a receipt. People buy or renew a key for someone?

2023-01-27 13:45 UTC, julien51 commented on subgraph/schema.graphql
> +  owner: String
That's a bad idea as a single receipt can apply to multiple keys for multiple owners.

2023-01-27 13:46 UTC, julien51 commented
Kali I removed the `owner` on purpose because there can be a single receipt for multiple okeys and owners. I don't understand why you need to add these values? Please clarify.

2023-01-27 13:54 UTC, kalidiagne commented
> Kali I removed the `owner` on purpose because there can be a single receipt for multiple okeys and owners. I don't understand why you need to add these values? Please clarify.

to retrieve all the receipts by `owner +keyId` in receipt page details.
I can just use the hash of the transactions eventually.

2023-01-30 14:35 UTC, julien51 requested changes
Can we closer this please as this is not the right approach?

2023-01-30 14:36 UTC, kalidiagne commented
yes, let's close it!

2023-01-30 14:36 UTC, closed without merging