fix(locksmith): lock managers and key owners can generate QR code
unlock-protocol/unlock pull request #11043
Opened 2023-02-14 21:51 UTC by julien51

# Description

A key owner and the lock manager should both be able to generate a QR code.

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2023-02-14 22:01 UTC, searchableguy requested changes

2023-02-14 22:01 UTC, searchableguy commented on locksmith/src/routes/v2/ticket.ts
> +import { lockManagerOrKeyOwnerMiddleware } from '../../utils/middlewares/lockManagerOrKeyOwner'
Need to add file to git?

2023-02-14 22:33 UTC, julien51 commented on locksmith/src/routes/v2/ticket.ts
> +import { lockManagerOrKeyOwnerMiddleware } from '../../utils/middlewares/lockManagerOrKeyOwner'
yes :D

2023-02-15 05:27 UTC, searchableguy approved these changes

2023-02-15 05:27 UTC, searchableguy commented on locksmith/src/utils/middlewares/lockManagerOrKeyOwner.ts
> +  const userAddress = Normalizer.ethereumAddress(req.user!.walletAddress!)
Normalizing isn't required. We already do it for user address.

2023-02-15 05:27 UTC, searchableguy commented on locksmith/src/utils/middlewares/lockManagerOrKeyOwner.ts
> +
Batch please.

2023-02-15 13:55 UTC, julien51 commented on locksmith/src/utils/middlewares/lockManagerOrKeyOwner.ts
> +  const userAddress = Normalizer.ethereumAddress(req.user!.walletAddress!)
```suggestion
  const userAddress = req.user!.walletAddress
```
Good point! Thanks

2023-02-15 14:07 UTC, julien51 commented on locksmith/src/utils/middlewares/lockManagerOrKeyOwner.ts
> +
Fixed!

2023-02-15 14:51 UTC, merged