feat(templates) - certification email templates
unlock-protocol/unlock pull request #11564
Opened 2023-04-06 17:59 UTC by kalidiagne

# Description

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2023-04-06 17:59 UTC, kalidiagne commented
@julien51 can you please review the copy?

2023-04-06 18:00 UTC, searchableguy approved these changes
I think we need some text changes but code wise LGTM

2023-04-06 22:07 UTC, julien51 commented on packages/email-templates/src/templates/certificationKeyAirdropped.ts
> +<p><a href="{{certificationUrl}}">Here</a> is your NFT certification (#{{keyId}}) for <strong>{{lockName}}</strong> was just airdropped!</p>
Eventually we can make these as PDF that are attached to the email

2023-04-06 22:08 UTC, julien51 commented on packages/email-templates/src/templates/certificationKeyAirdropped.ts
> +<p><a href="{{certificationUrl}}">Here</a> is your NFT certification (#{{keyId}}) for <strong>{{lockName}}</strong> was just airdropped!</p>
```suggestion
<p><a href="{{certificationUrl}}">Here</a> is your NFT certification (#{{keyId}}) for <strong>{{lockName}}</strong>. It was also just airdropped to your address.</p>
```

If the certification was airdropped by email we need to show the link to claim... please add that!

2023-04-06 22:08 UTC, julien51 commented on packages/email-templates/src/templates/certificationKeyAirdropped.ts
> +<p>It has been added to your <a href="{{keychainUrl}}">Unlock Keychain</a>, where you can view it and, if needed, print it as a signed QR Code!</p>
Only show that if it was indeed airdropped to the user's wallet... and if not show the link to claim it.

2023-04-06 22:11 UTC, julien51 commented on packages/email-templates/src/templates/certificationKeyMined.ts
> +<p><a href="{{certificationUrl}}">Here</a> is your NFT certification (#{{keyId}}) for <strong>{{lockName}}</strong> was just minted!</p>
```suggestion
  html: `<h1>A NFT certification for "{{lockName}}" was added to your wallet!</h1>
<p>Your NFT certification (#{{keyId}}) for <strong>{{lockName}}</strong> was just mined. You can <a href="{{certificationUrl}}">consult it directly</a> on this web page.</p>
```

2023-04-06 22:11 UTC, julien51 commented on packages/email-templates/src/templates/certificationKeyMined.ts
> +<p>It has been added to your <a href="{{keychainUrl}}">Unlock Keychain</a>, where you can view it and, if needed, print it as a signed QR Code!</p>
```suggestion
<p>It has been added to your <a href="{{keychainUrl}}">Unlock Keychain</a>, where you can view it and its metadata.</p>
```

2023-04-06 22:11 UTC, julien51 requested changes
Please fix the copy and add the link to claim.

2023-04-10 13:13 UTC, julien51 commented on packages/email-templates/src/templates/certificationKeyAirdropped.ts
> +  <p>It has been added to your <a href="{{keychainUrl}}">Unlock Keychain</a>, where you can view it and, if needed, print it as a signed QR Code!</p>
```suggestion
  <p>It has also been added to your <a href="{{keychainUrl}}">Unlock Keychain</a>, where you can view it and, if needed, print it as a signed QR Code!</p>
```

2023-04-10 13:13 UTC, julien51 commented on packages/email-templates/src/templates/certificationKeyAirdropped.ts
> +<p><a href="{{certificationUrl}}">Here</a> is your NFT certification (#{{keyId}}) for <strong>{{lockName}}</strong>. It was also just airdropped to your address.</p>
```suggestion
<p><a href="{{certificationUrl}}">Here</a> is your NFT certification (#{{keyId}}) for <strong>{{lockName}}</strong>. It was just airdropped to your address.</p>
```

2023-04-10 13:13 UTC, julien51 approved these changes

2023-04-10 17:02 UTC, merged