feat(subgraph) - receipt numbers
unlock-protocol/unlock pull request #11681
Opened 2023-04-19 11:59 UTC by kalidiagne

# Description

Add `receiptNumber` to subgraph  

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2023-04-19 13:00 UTC, julien51 requested changes
This is not right. The receipt number is not the number of keys... A receipt could exist for a transaction with multiple keys and a receipt could exist for a renewals (no new key).

2023-04-20 12:58 UTC, julien51 commented on subgraph/schema.graphql
> +  receiptCount: BigInt!
This is wrong. How can you keep track of the receipt count if you don't have a way to count them??

2023-04-20 13:25 UTC, kalidiagne commented on subgraph/schema.graphql
> +  receiptCount: BigInt!
we can rename to `numberOfReceipt` or add `receipts` and treat it like the `keys` as you suggested eventually

2023-04-20 13:38 UTC, julien51 commented on subgraph/schema.graphql
> +  receiptCount: BigInt!
```suggestion
  numberOfReceipts: BigInt!
```

2023-04-20 13:38 UTC, julien51 commented on subgraph/schema.graphql
> +  receiptNumber: BigInt
```suggestion
  numberOfReceipts: BigInt
```

2023-04-20 13:39 UTC, julien51 commented on subgraph/src/public-lock.ts
> +    lock.receiptCount = newReceiptNumber
```suggestion
    lock.numberOfReceipts = newReceiptNumber
```

2023-04-20 13:39 UTC, julien51 commented on subgraph/schema.graphql
> +  receiptCount: BigInt!
Ok let's do `numberOfReceipts` (with an `s`) and then it's good!

2023-04-20 13:39 UTC, julien51 approved these changes
LG!

2023-04-20 13:51 UTC, kalidiagne commented on subgraph/tests/locks.test.ts
> +    assert.fieldEquals('Lock', lockAddress, 'receiptCount', '0')
@julien51 awesome so ill update also test with `numberOfReceipts `

2023-04-20 16:36 UTC, merged