feat(unlock-app) - checkout config to event page
unlock-protocol/unlock pull request #12012
Opened 2023-05-30 15:55 UTC by kalidiagne

# Description
Set checkout config for a specific event as part of https://github.com/unlock-protocol/unlock/issues/11019 

This PR needs 

**Overview** 

<img width="500" alt="Screenshot 2023-05-31 at 16 52 16" src="https://github.com/unlock-protocol/unlock/assets/20865711/c7ecc8c5-6b5d-4958-9855-7ff98315ac86">

**Disabled check config** 

<img width="500" alt="Screenshot 2023-05-31 at 16 53 24" src="https://github.com/unlock-protocol/unlock/assets/20865711/db342dd7-3bcc-4a0b-af4e-a5a28e4c42e8">

**Set check config** 

<img width="500" alt="Screenshot 2023-05-31 at 16 53 45" src="https://github.com/unlock-protocol/unlock/assets/20865711/cb8aec51-1ccf-4385-90c7-a95732764623">

**Checkout config missing (lockManager)**  

<img width="500" alt="Screenshot 2023-05-30 at 13 29 04" src="https://github.com/unlock-protocol/unlock/assets/20865711/30317cbd-215b-45c7-b81a-bfa0ec981424">

**Checkout config missing (non-lockManager)**  

<img width="500" alt="Screenshot 2023-05-30 at 13 29 14" src="https://github.com/unlock-protocol/unlock/assets/20865711/47c313b6-6900-4db1-bdf7-2e43e7494cec">

**Registration options based on checkout config** 

<img width="600" alt="Screenshot 2023-05-31 at 16 45 47" src="https://github.com/unlock-protocol/unlock/assets/20865711/81640764-fc59-4d1a-99d4-717bf58b1e48">

**Registration modal **
 
<img width="500" alt="Screenshot 2023-05-30 at 15 39 36" src="https://github.com/unlock-protocol/unlock/assets/20865711/48458e34-0ff4-472a-9b58-ad619ed834c3">

**Verifiers (multiple locks in checkout config)**
 
<img width="500" alt="Screenshot 2023-05-31 at 16 34 03" src="https://github.com/unlock-protocol/unlock/assets/20865711/d79ecdbd-8d73-40b3-87bc-febbe33dbe39">

**Verifiers (multiple locks in checkout config)**

<img width="500" alt="Screenshot 2023-05-31 at 16 55 59" src="https://github.com/unlock-protocol/unlock/assets/20865711/41e48002-723f-4932-aa6e-5fe6b7da997d">

**Mobile** 
<img width="461" alt="Screenshot 2023-05-31 at 16 47 00" src="https://github.com/unlock-protocol/unlock/assets/20865711/e5524e06-a457-4ffd-a99d-471884a46e4e">

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2023-05-30 18:37 UTC, searchableguy approved these changes

2023-05-31 11:00 UTC, kalidiagne commented on unlock-app/src/components/content/event/EventCheckoutUrl.tsx
> +                            .
@julien51 can we improve copy here?

2023-05-31 11:00 UTC, kalidiagne commented on unlock-app/src/components/content/event/EventDetails.tsx
> +            : 'Registration details is not configured.'}
@julien51 can we improve copy here?

2023-05-31 11:01 UTC, kalidiagne commented on unlock-app/src/components/content/event/EventDetails.tsx
> +                description="Select one of their saved checkout URL that will be used for this event."
@julien51 can we improve copy here?

2023-05-31 13:59 UTC, julien51 commented on unlock-app/src/components/content/event/EventCheckoutUrl.tsx
> +          Create a checkout URL
```suggestion
          Create a new checkout URL, where you can configure the checkout steps for your event.
```

2023-05-31 14:00 UTC, julien51 commented on unlock-app/src/components/content/event/EventCheckoutUrl.tsx
> +                              Create a checkout URL
```suggestion
                              create a new one
```

2023-05-31 14:01 UTC, julien51 commented on unlock-app/src/components/content/event/EventDetails.tsx
> +            ? 'Your Checkout URL assigned to this event is deleted or not valid. Please make sure assign an existing one.'
```suggestion
            ? 'The checkout URL assigned to this event is deleted or invalid. Please make sure to assign an existing one.'
```

2023-05-31 14:01 UTC, julien51 commented on unlock-app/src/components/content/event/EventDetails.tsx
> +            : 'Registration details is not configured.'}
```suggestion
            : 'Registration details are not configured.'}
```

2023-05-31 14:02 UTC, julien51 approved these changes

2023-05-31 14:07 UTC, kalidiagne commented on unlock-app/src/components/content/event/EventCheckoutUrl.tsx
> +            title="Set Checkout URL."
```suggestion
            title="Set Checkout URL"
```

2023-05-31 14:07 UTC, julien51 requested changes
Please add back verifiers for the locks. Just list all the locks and the corresponding verifier.

2023-05-31 17:22 UTC, julien51 approved these changes

2023-05-31 17:42 UTC, merged