feat(locksmith) - refactor lock-settings endpoint
unlock-protocol/unlock pull request #12075
Opened 2023-06-01 17:11 UTC by kalidiagne

# Description

- [x] Allow anyone to call `/v2/lock-settings/{network}/locks/{lockAddress}`
- [x] `/v2/lock-settings/{network}/locks/{lockAddress}` should not include sensitive details when no user is connected or the connected user is not the lock manager 

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [x] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2023-06-01 17:31 UTC, julien51 commented on locksmith/__tests__/controllers/v2/lockSettingController.test.ts
> -  it('should fail to get settings  with no authentication', async () => {
Please add tests to make sure when the call is authenticated it includes the right data and when not authenticated it does not include it!

2023-06-01 17:32 UTC, julien51 commented on locksmith/src/controllers/v2/lockSettingController.ts
> +    const isLockManager = await web3Service.isLockManager(
Only make that call if `userAddress` is set

2023-06-01 17:33 UTC, julien51 requested changes
Please write tests

2023-06-01 21:02 UTC, kalidiagne commented
> Please write tests

Tests updated

2023-06-02 00:37 UTC, julien51 commented on locksmith/__tests__/operations/lockSettingsOperations.test.ts
> +  it.only('correctly save and retrieve lock settings without protected data', async () => {
remove `.only`

2023-06-02 00:40 UTC, julien51 approved these changes

2023-06-02 00:40 UTC, julien51 commented on locksmith/src/operations/lockSettingOperations.ts
> +    attributes: {
I like this approach!

2023-06-02 00:47 UTC, merged