feat(unlock-app) - Update destination for CTA buttons on EVENTS
unlock-protocol/unlock pull request #12382
Opened 2023-07-18 14:38 UTC by kalidiagne

# Description
- Update destination for CTA buttons on EVENTS 

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2023-07-22 18:09 UTC, ccarfi commented
@kalidiagne i clicked on the CTA buttons in the netlify staging build, and they still seem to go to the old (open metamask) location instead of the new (land on hubspot lead capture form) location. can you please confirm this opens the hubspot form when either of the in-page CTA buttons are clicked? thanks.

2023-07-22 20:09 UTC, searchableguy approved these changes

2023-07-24 06:39 UTC, julien51 requested changes
I don't think it would be that hard to add the form to the actual existing flow AND save it into Hubspot. I think it would significantly reduce friction/weirdness. Any reason why you would not want to do it?

2023-07-24 13:31 UTC, julien51 approved these changes

2023-07-24 16:38 UTC, merged