feat(networks): add support for Base sepolia
unlock-protocol/unlock pull request #13529
Opened 2024-03-27 13:58 UTC by clemsos

# Description

This adds support for Base Sepolia

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2024-03-27 14:11 UTC, clemsos commented
While creating from frontend locally I am getting the following error

![Screenshot 2024-03-27 at 15 11 13](https://github.com/unlock-protocol/unlock/assets/743246/e343c3f6-844c-40aa-b46f-078d177b10b3)

2024-03-27 14:14 UTC, clemsos commented
Creating a lock from unlock-app works locally but the UI crash (likely because it is trying to fetch data from staging)

2024-03-27 19:50 UTC, julien51 commented
> Creating a lock from unlock-app works locally but the UI crash (likely because it is trying to fetch data from staging)

Hum. Maybe from the subgraph?

We should try to get down to the bottom of what exactly fails?

2024-03-27 19:52 UTC, julien51 commented on packages/networks/src/networks/base-sepolia.ts
> +  provider: 'https://sepolia.base.org',
Ok I'll deploy that shortly!

2024-03-27 19:52 UTC, julien51 approved these changes

2024-03-27 23:31 UTC, julien51 commented on packages/networks/src/networks/base-sepolia.ts
> +  provider: 'https://sepolia.base.org',
```suggestion
  provider: 'https://rpc.unlock-protocol.com/84532',
```

2024-03-27 23:34 UTC, julien51 requested changes
I run the health check script:

```
[Base Sepolia (84532)]: 0x68F2c5D9009dc4d553f814D689102a53B2b349Cc ❌ Policy below 2!
[Base Sepolia]: ⚠️  ProxyAdmin owner is not the team multisig
[Base Sepolia]: ⚠️  Unlock owner is not the team multisig
```

Please make sure you set it correctly so we don't have any issue later!!

2024-03-27 23:35 UTC, julien51 commented
I would love to find a way to run these scripts as part of CI when adding new networks!

2024-03-27 23:37 UTC, julien51 commented
Also I have deployed the provider :)

2024-03-29 13:37 UTC, clemsos commented
ok ownership of the contracts have been transferred

2024-03-29 15:02 UTC, julien51 commented
Thx! Tested and LGTM

2024-03-29 19:00 UTC, merged