feat(governance): proposal to deploy contract across chain
unlock-protocol/unlock pull request #14113
Opened 2024-06-27 09:55 UTC by clemsos

# Description

This adds a proposal that uses the cross-chain pattern to deploy contract from the DAO to another chain using the Connext bridge 

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2024-06-28 18:41 UTC, julien51 approved these changes

2024-06-28 18:42 UTC, julien51 commented on governance/proposals/014-deploy-up-udt-swap.js
> +// TODO : change to base
YES!

2024-06-28 18:43 UTC, julien51 requested changes
I would be in favor of splitting this in 2 PRs. One for the Connext changes and one for the proposal to deploy the swapping contract so we can point to this more easily!

2024-07-01 12:44 UTC, clemsos commented
> I would be in favor of splitting this in 2 PRs. One for the Connext changes and one for the proposal to deploy the swapping contract so we can point to this more easily!

Right. The changes related to bridge have been moved here https://github.com/unlock-protocol/unlock/pull/14204

2024-07-04 18:32 UTC, clemsos commented
We didn't need to deploy across chain so closing this

2024-07-04 18:32 UTC, closed without merging