feat(unlock-app): Support ENS in checkout builder for Referrer field
unlock-protocol/unlock pull request #14239
Opened 2024-07-05 15:58 UTC by sudheerDev

# Description

 * Add changes to use AddressField component to resolve ens in checkout builder form
 * Change getReferrer util to resolve ens if it is present in config
 * Add changes to instances of getReferrer to be async

# Issues

Fixes # https://github.com/unlock-protocol/unlock/issues/14102
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2024-07-13 08:22 UTC, sudheerDev commented
Did a transaction with checkout builder https://staging-app.unlock-protocol.com/checkout?id=3fb9a5df-0831-4f03-a39e-4597a69a90ed which has ens set in referrer config.

2024-07-17 20:49 UTC, julien51 commented on unlock-app/src/components/interface/checkout/main/Confirm/ConfirmCard.tsx
> +  useEffect(() => {
Since this code is duplicated, what about introducing a `useReferrers` hook (inside of the `hooks` folder) that we can re-use more easily?

2024-07-17 20:50 UTC, julien51 commented on unlock-app/src/components/interface/checkout/main/Confirm/ConfirmCard.tsx
> +    referrers,
I suspect we should handle `getReferrer` taking more time to load? wdyt?

2024-07-17 20:52 UTC, julien51 commented on unlock-app/src/components/interface/keychain/Extend.tsx
> +        referrer,
```suggestion
        referrer: await getReferrer(account!),
```

2024-07-17 20:53 UTC, julien51 requested changes
I think we dn't need to use `useEffect` at all.

2024-07-18 13:21 UTC, sudheerDev commented on unlock-app/src/components/interface/keychain/Extend.tsx
> +        referrer,
Already does this above

2024-07-18 21:03 UTC, julien51 commented on unlock-app/src/components/interface/keychain/Extend.tsx
> +        referrer,
yeah yeah I was just simplifying a bit!

2024-08-29 20:42 UTC, julien51 commented
@sudheerDev Any progress here? Please let us know if we should close.

2024-09-04 05:36 UTC, sudheerDev commented
@julien51 Hey, sorry. I will close this for now. I will open it again addressing comments if no one grabs this.

2024-09-04 05:36 UTC, closed without merging