feat(smart-contracts): replace `udt` by `governanceToken` in Unlock contract
unlock-protocol/unlock pull request #14688
Opened 2024-09-27 12:54 UTC by clemsos

# Description

This replaces UDT with `governanceToken` in contracts

# Issues

Fixes #14658
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2024-09-27 14:28 UTC, julien51 commented on smart-contracts/contracts/Unlock.sol
> -  address public udt;
We should probably keep that and mark it as deprecated in favor of `governanceToken` to avoid breaking 3rd parties?

2024-09-27 14:30 UTC, julien51 requested changes
Let's keep the `udt()` signature for compatinbility!

2024-09-30 13:43 UTC, clemsos commented on smart-contracts/test/UPToken/swap.js
> +      assert.equal(await swap.governanceToken(), await udt.getAddress())
```suggestion
      assert.equal(await swap.udt(), await udt.getAddress())
```

2024-09-30 13:55 UTC, clemsos commented on smart-contracts/test/UnlockSwapBurner/swapAndBurn.mainnet.js
> +    udtAddress = await unlock.governanceToken()
```suggestion
    udtAddress = await unlock.udt()
```

2024-10-04 13:57 UTC, julien51 commented on smart-contracts/contracts/Unlock.sol
> +  // however, the `governanceToken` getter is now preferred
```suggestion
  // DEPRECATED: udt was the name of the first governance token. 
  // Kept for backward compatibility; however, the `governanceToken` getter is now preferred.
```

2024-10-04 13:58 UTC, julien51 approved these changes

2024-10-11 13:23 UTC, merged