feature(packages/ui): `Combobox` component
unlock-protocol/unlock pull request #14814
Opened 2024-10-07 09:17 UTC by 0xTxbi

# Description
This PR introduces a new `Combobox` component to our `ui` package, aimed at improving user experience and accessibility over traditional select elements. It includes a dynamic search functionality, making it easier for users to filter and locate options within large datasets. It also supports full keyboard navigation (`enter`, Arrow keys, `escape`, `tab`) for enhanced accessibility compliance. 

Additional features include customizable prepend/append elements, disabled states, and clear visual feedback with check icons, all integrated with our `FieldLayout` for consistent styling.

Overall, it simplifies dropdown selection.

## ScreenGrab
<img width="1524" alt="Screenshot 2024-10-07 at 10 12 22" src="https://github.com/user-attachments/assets/ffa4d7e9-ea83-483b-89be-8c321b3dd577">

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [x] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

2024-10-07 14:12 UTC, julien51 commented
ok ok, this definetely "looks" good and useful, but I want to make sure it "blends" in our existing style. wdyt?

2024-10-07 14:43 UTC, 0xTxbi commented
> ok ok, this definetely "looks" good and useful, but I want to make sure it "blends" in our existing style. wdyt?

good question, and yes it does blend with our existing style and branding! do check this [demo](https://www.loom.com/share/aab8d0516ee94ffe9f3680ee39ce8a4e)

2024-10-07 19:20 UTC, julien51 commented
ok I think we are missing the "more" options here. It is important because it lets us show a smaller number of options by default but if the use r wants more, then more are shown. Do you think you could add that?

2024-10-07 21:11 UTC, 0xTxbi commented
> ok I think we are missing the "more" options here. It is important because it lets us show a smaller number of options by default but if the use r wants more, then more are shown. Do you think you could add that?

good point! will add that!

2024-10-09 13:47 UTC, julien51 reviewed
Hum, I am not sure I see the `moreOptions` option.
The goal here is to show a specifc subset of items by default (not just the first n...)

2024-10-17 14:50 UTC, julien51 commented on packages/ui/lib/components/Form/Combobox.tsx
> +  initialOptions: Option[]
Let's just keep `options` here for backward compatibility!

2024-10-17 14:50 UTC, julien51 commented on packages/ui/lib/components/Form/Combobox.tsx
> +  initialOptions: Option[]
```suggestion
  options: Option[]
```

2024-10-25 19:03 UTC, julien51 commented on packages/ui/lib/components/Form/Combobox.stories.tsx
> +    initialOptions: getRandomItems(allOptions, 5),
shouldn't that be `options` ?

2024-10-25 19:04 UTC, julien51 requested changes
I think the stories need to be updated, no?

2024-10-25 19:04 UTC, julien51 commented on packages/ui/lib/components/Form/Combobox.stories.tsx
> +    initialOptions: getRandomItems(allOptions, 5),
same?

2024-10-25 19:04 UTC, julien51 commented on packages/ui/lib/components/Form/Combobox.stories.tsx
> +    initialOptions: getRandomItems(
same?

2024-10-25 19:04 UTC, julien51 commented on packages/ui/lib/components/Form/Combobox.stories.tsx
> +    initialOptions: getRandomItems(allOptions, allOptions.length),
ditto

2024-10-25 19:04 UTC, julien51 commented on packages/ui/lib/components/Form/Combobox.stories.tsx
> +    initialOptions: getRandomItems(allOptions, 5),
and there as well?

2024-10-25 19:05 UTC, 0xTxbi commented
> I think the stories need to be updated, no?

oh definitely. the push failed for some reason!

2024-10-25 19:06 UTC, julien51 approved these changes

2024-10-25 19:23 UTC, merged