Add proposals october 2024
unlock-protocol/unlock pull request #14849
Opened 2024-10-17 02:17 UTC by pi0neerpat

# Description

Adding new governance proposals

2024-11-06 00:17 UTC, pi0neerpat commented
Updated the proposals to match the framework. Run with:

```bash
RUN_FORK=8453 yarn hardhat gov --gov-address 0x65bA0624403Fc5Ca2b20479e9F626eD4D78E0aD9 \
  --proposal proposals/up/002-change-voting-duration.js --show-stack-traces

RUN_FORK=8453 yarn hardhat gov --gov-address 0x65bA0624403Fc5Ca2b20479e9F626eD4D78E0aD9 \
  --proposal proposals/up/003-increase-proposal-threshold.js --show-stack-traces
```

2024-11-06 07:11 UTC, clemsos requested changes

2024-11-06 07:11 UTC, clemsos commented on governance/proposals/up/002-change-voting-duration.js
> +const BASE_UP_TIMELOCK_ADDRESS = '0xB34567C4cA697b39F72e1a8478f285329A98ed1b'
It is better to get the time lock address through the gov contract instead of hardcoding it to prevent possible mistakes

2024-11-06 07:11 UTC, clemsos commented on governance/proposals/up/002-change-voting-duration.js
> +      functionArgs: [345600],
Can we do sth more explicit, like DAYS * 4 where days is the number of seconds in a day ?

2024-11-06 07:11 UTC, clemsos commented on governance/proposals/up/003-increase-proposal-threshold.js
> +const BASE_UP_GOVERNOR_ADDRESS = '0x65bA0624403Fc5Ca2b20479e9F626eD4D78E0aD9'
That address can now be fetched from the networks package https://github.com/unlock-protocol/unlock/blob/5580b88715c348444a9a6586d28c570a15f3f4fd/packages/networks/src/networks/base.ts#L18

2024-11-06 07:11 UTC, clemsos commented on governance/proposals/up/003-increase-proposal-threshold.js
> +      functionArgs: ['50000000000000000000000'],
Same here, could we parse it as a more explicit form, like import ethers parseEther helper or use 10**18 notation for BigInt ?

2024-11-06 07:11 UTC, clemsos commented on governance/proposals/up/004-10_9_2024-71822073-UP Gamma Incentives.json
This one needs refactoring as formatting doesn't follow what is expected from a proposal file. Also we can't have arbitrary call data without explanations as it makes it impossible to review

2024-11-06 07:12 UTC, clemsos commented
The first two good so far, except for some small issues with readability and consistency. The last one is more mysterious and needs to be rewritten imo

2024-11-12 22:40 UTC, julien51 commented
Let's close as this won't pass anyway.

2024-11-12 22:40 UTC, closed without merging