fix(unlock-app) Rounding
unlock-protocol/unlock pull request #8789
Opened 2022-05-10 20:11 UTC by julien51

# Description

Fixing rounding UI issue.

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2022-05-10 20:30 UTC, searchableguy requested changes

2022-05-10 20:30 UTC, searchableguy commented on unlock-app/src/components/helpers/BalanceProvider.js
> +  console.log(typeof ethWithPresentation)
Remove the unnecessary log?

2022-05-10 20:30 UTC, searchableguy commented on unlock-app/src/components/interface/verification/Key.tsx
> +      }
Didn't you fix this in another PR?

2022-05-11 01:34 UTC, julien51 commented on unlock-app/src/components/interface/verification/Key.tsx
> +      }
Yes, I need a rebase. sorry!

2022-05-11 01:34 UTC, julien51 commented on unlock-app/src/components/helpers/BalanceProvider.js
> +  console.log(typeof ethWithPresentation)
```suggestion
```

2022-05-11 01:42 UTC, julien51 commented
/rebase

2022-05-11 02:14 UTC, merged