fix(locksmith): workaround for polygon `maxFeePerGas` setttings in ethers 5
unlock-protocol/unlock pull request #8837
Opened 2022-05-17 17:25 UTC by clemsos

# Description

Because of settings introduced in Ethers 5.6.1 (described [here](https://github.com/ethers-io/ethers.js/issues/2828)), tx sent on polygon from locksmith are failing with a `tx underpriced` error. This adds a workaround where we fetch expected gas fees directly from Polygon gas station

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2022-05-18 15:05 UTC, julien51 commented on locksmith/src/fulfillment/dispatcher.ts
> +        'gwei'
Let's multiple here too please :)

2022-05-18 15:50 UTC, julien51 requested changes
Small change to make sure we still bump prio on polygon

2022-05-18 16:47 UTC, clemsos commented on locksmith/src/fulfillment/dispatcher.ts
> +      )
Oh ok. We can also just use the `data.fast` estimate - I used the `data.standard` here

2022-05-18 19:37 UTC, julien51 commented on locksmith/src/utils/gasSettings.ts
> +      )
```suggestion
      ).mul(2)
```

2022-05-19 00:37 UTC, julien51 approved these changes

2022-05-19 00:38 UTC, julien51 commented
I'll merge so I can do a prod deploy! Thank you...

2022-05-19 00:38 UTC, merged