feat(locksmith) - add lock manager support in verifiers endpoint
unlock-protocol/unlock pull request #8969
Opened 2022-06-03 17:42 UTC by kalidiagne

# Description
This PR adds
- add more security by checking for verifiers endpoints
  -  if logged user is `lockManager`, can use the endpoints without any un-authorized error message 
- Spinner on loading when when `/verifiers/list/[...]` is retrieving data
- endpoint to check a specific verifier for and address ( defined in `isVerifierEnabled` )

# Issues

Fixes #
Refs #

<img width="1022" alt="Screenshot 2022-06-03 at 19 12 13" src="https://user-images.githubusercontent.com/20865711/171917865-2740daae-2368-4707-aee8-949d2bf96aa3.png">
# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2022-06-03 18:56 UTC, julien51 commented on locksmith/src/controllers/v2/verifierController.ts
> +      const isLockManager = await this.#isLockManager({
Good catch!

2022-06-03 18:56 UTC, julien51 commented on locksmith/src/controllers/v2/verifierController.ts
> +      const isLockManager = await this.#isLockManager({
Maybe do that only if `isVerifier` is `false`?

2022-06-03 18:58 UTC, julien51 commented on locksmith/src/controllers/v2/verifierController.ts
> +  async isVerifierEnabled(request: Request, response: Response) {
This is good, and we will need to make sure that the `request.params.verifierAddress` matches the token on the API request too!

2022-06-03 18:58 UTC, julien51 approved these changes

2022-06-04 08:27 UTC, searchableguy commented on locksmith/src/controllers/v2/verifierController.ts
> +      const isLockManager = await this.#isLockManager({
Wasn't this handled in a middleware?

2022-06-06 09:25 UTC, kalidiagne commented on locksmith/src/controllers/v2/verifierController.ts
> +      const isLockManager = await this.#isLockManager({
oh, you're right!

2022-06-06 19:50 UTC, julien51 commented on locksmith/src/controllers/v2/verifierController.ts
> +      const verifierMatchesLoggedUser = request.user?.walletAddress === address
That is not right (I think my comment was misleading!). We need to verify that `request.user?.walletAddress` is a lock manager on the lock...

2022-06-06 19:50 UTC, julien51 commented on locksmith/src/controllers/v2/verifierController.ts
> +      const verifierMatchesLoggedUser = request.user?.walletAddress === address
Actually I think my comment was misleading, sorry :/

2022-06-06 19:57 UTC, julien51 requested changes
I am sorry for the confusion here.
I see multiple problems. First `getVerifiersList` should return __all__ the verifiers, not just the ones matching the lockManager` (I actually think we should not use `lockManager` in that function).

Then the `list` function should check that `request.user!.walletAddress!` is indeed a `lockManager` and fail if not. (only a lock manager should be able to see the list of verifiers)
Sinilarly the functions to add/remove verifiers can only be called by a lock manager.

Finally, I am not sure what `isVerifierEnabled` is used for?

2022-06-06 20:20 UTC, kalidiagne commented
> I am sorry for the confusion here. I see multiple problems. First `getVerifiersList` should return **all** the verifiers, not just the ones matching the lockManager`(I actually think we should not use`lockManager` in that function).
> 
> Then the `list` function should check that `request.user!.walletAddress!` is indeed a `lockManager` and fail if not. (only a lock manager should be able to see the list of verifiers) Sinilarly the functions to add/remove verifiers can only be called by a lock manager.
> 
> Finally, I am not sure what `isVerifierEnabled` is used for?

@julien51  Changed `getVerifiersList ` as suggested, without the use of `lockManager`

Also
- All the routes use `lockManagerMiddleware`, so only lockManager can call it.
- `isVerifierEnabled` is needed for #8966, basically to check if the user is a verifier of a specific lock, and eventually to enable it on the verification page

2022-06-07 13:27 UTC, julien51 commented on locksmith/src/controllers/v2/verifierController.ts
> +          message: `User not authozired`,
```suggestion
          message: `User not authorized`,
```

2022-06-07 13:30 UTC, julien51 commented
> @julien51 Changed `getVerifiersList ` as suggested, without the use of `lockManager`

Thank you!

> * All the routes use `lockManagerMiddleware`, so only lockManager can call it.

Oh wow, I had missed that! Thank you, that clarifies it...

> * `isVerifierEnabled` is needed for [feat(unlock-app) - add verifier check into verification page #8966](https://github.com/unlock-protocol/unlock/pull/8966), basically to check if the user is a verifier of a specific lock, and eventually to enable it on the verification page

Ok I misunderstood what that function was for but now I think I get it! 

Thanks! Approved!

2022-06-07 14:39 UTC, merged