feat(unlock-app) - add explicit button to scan next ticket
unlock-protocol/unlock pull request #9249
Opened 2022-07-13 17:15 UTC by kalidiagne

# Description
Add ability to scan next ticket from the UI when ticket is already marked as check-in 

# Issues

Fixes #
Refs #
<img width="821" alt="Screenshot 2022-07-13 at 19 14 03" src="https://user-images.githubusercontent.com/20865711/178792193-89b1d64b-4703-4c9d-92d7-39ab37a061ba.png">

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2022-07-13 17:19 UTC, searchableguy commented on unlock-app/src/components/interface/VerificationStatus.tsx
> +  setConfig: (config: MembershipVerificationConfig | null) => void
Rename this to generic onScanNext function. We should expose assume anything about how the parent deals with state above. Let them pass a generic function which is called when x happens.

2022-07-13 17:21 UTC, searchableguy commented on unlock-app/src/components/interface/verification/Scanner.tsx
> +                      setConfig={setMembershipVerificationConfig}
Should be `onVerified={() => { setMembershipVerificationConfig(null) }}`

2022-07-13 17:22 UTC, searchableguy requested changes
You need to deal with how redirect on the verification page as well here.

2022-07-13 17:28 UTC, julien51 commented
> You need to deal with how to redirect on the verification page as well here.

Can you clarify please?

2022-07-13 21:07 UTC, julien51 commented
> Outside of scanner, the verification page which shows the status when you use the full URL. We should have a scan button there well, right?

Makes sense and yes! Thank you!

2022-07-13 21:07 UTC, julien51 approved these changes

2022-07-14 08:59 UTC, searchableguy commented on unlock-app/src/components/interface/VerificationStatus.tsx
> +    console.log('onVerifiedCb', onVerified)
Remove

2022-07-14 09:58 UTC, merged