feat(unlock-protocol-com) - add upcoming events page
unlock-protocol/unlock pull request #9332
Opened 2022-07-27 16:37 UTC by kalidiagne

# Description
- Add upcoming events page

# Issues

Fixes #
Refs #
<img width="1566" alt="Screenshot 2022-07-27 at 18 33 17" src="https://user-images.githubusercontent.com/20865711/181301830-791271b1-d550-475e-9e0b-029ded37aad0.png">

<img width="617" alt="Screenshot 2022-07-27 at 18 37 19" src="https://user-images.githubusercontent.com/20865711/181302005-34b81211-9384-48dd-bd0f-0d1889ae1f02.png">

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2022-07-27 17:30 UTC, kalidiagne commented on unlock-protocol-com/src/components/pages/Events/index.tsx
> +          <Button variant="secondary">Add to Calendar</Button>
Oh yes, is secondary in design

2022-07-28 09:43 UTC, kalidiagne commented on unlock-protocol-com/src/components/pages/Events/index.tsx
> +          <Button variant="secondary">Add to Calendar</Button>
Added component

2022-07-28 10:02 UTC, kalidiagne commented on unlock-protocol-com/src/components/pages/Events/index.tsx
> +          <Button variant="secondary">Add to Calendar</Button>
changed with `primary`

2022-07-28 10:06 UTC, julien51 commented
@kalidiagne It looks like events are not sorted?
I think it would be nice to show _all_ events but the ones in the past are slightly greyed out and the button disabled? wdyt @ChialiTsai ?

2022-07-28 11:15 UTC, kalidiagne commented on unlock-protocol-com/src/components/pages/Events/index.tsx
> +      <section className="grid grid-cols-1 gap-[32px] py-[40px] lg:grid-cols-3">
yep! changed with the default one!

2022-07-28 11:17 UTC, kalidiagne commented
> @kalidiagne It looks like events are not sorted? I think it would be nice to show _all_ events but the ones in the past are slightly greyed out and the button disabled? wdyt @ChialiTsai ?

Sorted events and added link to calendar (screen attached), waiting for @ChialiTsai feedback!

2022-07-28 12:54 UTC, julien51 commented
@kalidiagne : 
> the ones in the past are slightly greyed out and the button disabled? wdyt @ChialiTsai ?

2022-07-28 13:02 UTC, kalidiagne commented on unlock-protocol-com/tailwind.config.js
> +  plugins: [require('@tailwindcss/line-clamp')],
awesome! i'll remove

2022-07-28 15:26 UTC, kalidiagne commented
**Future and past events**

<img width="1522" alt="Screenshot 2022-07-28 at 17 22 49" src="https://user-images.githubusercontent.com/20865711/181576619-d7f8b9fc-8748-4acf-a0e5-3cbe4412369b.png">

2022-07-28 15:27 UTC, kalidiagne commented
what about ignoring events without description and location as this example? 

<img width="857" alt="Screenshot 2022-07-28 at 17 25 35" src="https://user-images.githubusercontent.com/20865711/181576766-0db0967f-a301-424b-84d4-b9f20fd5d948.png">

@julien51 @ChialiTsai

2022-07-28 16:42 UTC, kalidiagne commented
**Placeholder**

<img width="600" alt="Screenshot 2022-07-28 at 18 35 56" src="https://user-images.githubusercontent.com/20865711/181592276-0660a0c8-b9b9-4e37-8963-ba3d98bac747.png">

2022-07-28 17:02 UTC, ChialiTsai commented
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/16527634/181595788-3d96b3bc-0e4b-4c62-90f9-52e402acfc73.png">



@kalidiagne is it possible to hide the past event add to calendar btn?

2022-07-28 17:04 UTC, kalidiagne commented
> <img alt="image" width="1015" src="https://user-images.githubusercontent.com/16527634/181595788-3d96b3bc-0e4b-4c62-90f9-52e402acfc73.png">
> 
> @kalidiagne is it possible to hide the past event add to calendar btn?

sure! done!

2022-07-28 17:07 UTC, kalidiagne commented on unlock-protocol-com/src/utils/calendar.ts
> +    const calendarRaw = await fetch(fileUrl).then((res) => res.text())
getting data from url 

`https://calendar.google.com/calendar/ical/c_dm3gud9ph6jqk7epq6jtij8u00%40group.calendar.google.com/public/basic.ics`
actually from localhost bypassing with cors plugin gonna work online? 
@searchableguy

2022-07-29 06:18 UTC, julien51 commented
@kalidiagne I tested and it does not work https://62e2c9dc311c8f0068b12403--unlock-protocol-com-staging.netlify.app/upcoming-events

You need to generate the page content at build time.... so that you don't have CORS issues.

2022-07-29 09:39 UTC, julien51 commented on unlock-protocol-com/package.json
> +    "cal-parser": "^1.0.2",
Remove carets please!

2022-07-29 09:39 UTC, kalidiagne commented
Updated and checked also that event time renders with timezone time

<img width="1565" alt="Screenshot 2022-07-29 at 11 35 11" src="https://user-images.githubusercontent.com/20865711/181731417-bf333770-8f47-48e3-9d7c-f0ca96633acd.png">

<img width="1627" alt="Screenshot 2022-07-29 at 11 34 41" src="https://user-images.githubusercontent.com/20865711/181731421-3377a604-90d4-43ca-8ced-15ede9d6a0ce.png">


<img width="1643" alt="Screenshot 2022-07-29 at 11 35 24" src="https://user-images.githubusercontent.com/20865711/181731402-37c020e2-f1d7-42b1-b61a-50a862cc9da6.png">

2022-07-29 09:40 UTC, julien51 commented on unlock-protocol-com/src/config/routes.tsx
> +      description: 'Join us for AMA, Governance and other activities ',
```suggestion
      description: 'Join the Unlock Protocol community and core teams for conferences, workshops, AMA, Governance and, other activities',
```

2022-07-29 09:42 UTC, julien51 requested changes
LG, please test in the draft built (especially the links...)

2022-07-29 09:42 UTC, julien51 commented on unlock-protocol-com/package.json
> +    "cal-parser": "^1.0.2",
(and run `yarn`)

2022-07-29 09:42 UTC, julien51 approved these changes

2022-07-29 10:51 UTC, julien51 commented
Woot! LGTM! Let's merge please!

2022-07-29 12:10 UTC, merged