feat(unlock-app) - fixing user creation
unlock-protocol/unlock pull request #9528
Opened 2022-08-30 08:35 UTC by kalidiagne

# Description
- Fix user creation issue on `POST` endpoint
- Replace Input/Button components 

# Issues

Fixes #
Refs #
<img width="700" alt="Screenshot 2022-08-30 at 10 05 48" src="https://user-images.githubusercontent.com/20865711/187389884-f2caa845-febc-41d5-9e6d-0ca82dddba16.png">

<img width="700" alt="Screenshot 2022-08-30 at 10 11 26" src="https://user-images.githubusercontent.com/20865711/187389903-7952c81c-cf4c-4a0e-a975-231150e9d217.png">

<img width="700" alt="Screenshot 2022-08-30 at 10 12 00" src="https://user-images.githubusercontent.com/20865711/187389917-065aff70-45fb-424a-85fe-212b2e4702de.png">

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2022-08-30 13:52 UTC, julien51 commented
💅

2022-08-30 13:53 UTC, julien51 commented on unlock-app/src/hooks/useAccount.ts
> +      const successCodes = [200, 201, 204]
Agreed this is very fragile, what happens on 403 or 500?

2022-08-30 13:54 UTC, julien51 requested changes
This is looking very good! 
Please fix the HTTP request check and maybe center terms as @searchableguy suggested!

2022-08-30 16:01 UTC, kalidiagne commented
Content centred, and added styles also for Login page

<img width="600" alt="Screenshot 2022-08-30 at 17 43 47" src="https://user-images.githubusercontent.com/20865711/187485111-950adf63-ed8f-4ffd-ad39-b63e699d2b0f.png">

<img width="600" alt="Screenshot 2022-08-30 at 17 52 15" src="https://user-images.githubusercontent.com/20865711/187485118-671966e3-8f60-4b79-a5d6-6f8aabc53842.png">

<img width="600" alt="Screenshot 2022-08-30 at 17 57 38" src="https://user-images.githubusercontent.com/20865711/187485122-715462e4-5027-45b6-9a0a-e0efd08af258.png">

2022-08-31 15:28 UTC, julien51 commented
Also please don't do buttons for "Login" and "connect it" or "cancel"... they look really strange

2022-08-31 16:49 UTC, kalidiagne commented
Asked help to @ChialiTsai for new design so i can update it all with new UI

2022-09-01 08:50 UTC, kalidiagne commented
- Resized text with better hierarchy
- Remove button for "Login" and "connect it" or "cancel"
- Add more space between form fields and titles 

<img width="600" alt="Screenshot 2022-09-01 at 10 47 00" src="https://user-images.githubusercontent.com/20865711/187873417-be6ace0b-3e74-42ef-8820-ac7dfc0e8848.png">

<img width="600" alt="Screenshot 2022-09-01 at 10 47 08" src="https://user-images.githubusercontent.com/20865711/187873425-1a3cf7d6-7b61-4d3e-bc71-e702d4789674.png">

<img width="600" alt="Screenshot 2022-09-01 at 10 49 02" src="https://user-images.githubusercontent.com/20865711/187873432-39c5cfe1-c6be-4a97-b61f-5f77c5a9f94f.png">

2022-09-01 13:07 UTC, julien51 approved these changes

2022-09-01 13:09 UTC, merged