feat(unlock-app) - custom contract address
unlock-protocol/unlock pull request #9601
Opened 2022-09-13 15:53 UTC by kalidiagne

# Description
Custom contract address on lock creation.

https://user-images.githubusercontent.com/20865711/189948633-a3e5063f-eb24-4c45-8fb2-f226b544939d.mov

**Modal** 
<img width="553" alt="Screenshot 2022-09-13 at 16 53 51" src="https://user-images.githubusercontent.com/20865711/189948189-0b69c5e2-4d91-4916-b36d-61eef1f778fe.png">

**Created lock with correct symbol** 
<img width="1425" alt="Screenshot 2022-09-13 at 17 47 29" src="https://user-images.githubusercontent.com/20865711/189948234-5d8f59dd-a221-4a96-b8f9-7af1610637d5.png">

# Issues

Fixes #
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2022-09-13 19:35 UTC, julien51 commented
Please, make sure we add the "default" currency to the list too... because right now if I select a token, I can't go back to eth...

2022-09-13 19:38 UTC, julien51 requested changes
i th

2022-09-14 09:57 UTC, kalidiagne commented
> Please, make sure we add the "default" currency to the list too... because right now if I select a token, I can't go back to eth...

<img width="600" alt="Screenshot 2022-09-14 at 11 54 49" src="https://user-images.githubusercontent.com/20865711/190123710-b22d927c-f524-4da6-ae6b-e5598c8f6b44.png">

2022-09-15 02:14 UTC, julien51 approved these changes

2022-09-15 05:36 UTC, merged