feat(unlock-app): Add email option in paywall config for automatic collection of email
unlock-protocol/unlock pull request #9609
Opened 2022-09-15 07:32 UTC by searchableguy

# Description

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2022-09-15 10:14 UTC, julien51 requested changes
Just a few nits and then lg.
Please make sure to add the corresponding docs too

2022-09-15 22:56 UTC, julien51 commented on unlock-app/src/components/interface/checkout/alpha/Checkout/Metadata.tsx
> +      placeholder: 'unlock-protocol@gmail.com',
```suggestion
      placeholder: 'hello@unlock-protocol.com',
```

2022-09-15 22:56 UTC, julien51 approved these changes

2022-09-15 22:57 UTC, julien51 commented
> Please make sure to add the corresponding docs too

Please @searchableguy make sure you add some docs on https://docs.unlock-protocol.com/tools/checkout/configuration

2022-09-16 00:53 UTC, searchableguy commented
will do after merging

2022-09-16 00:53 UTC, merged