feat(unlock-app): Support forever in recurring option
unlock-protocol/unlock pull request #9935
Opened 2022-10-13 14:15 UTC by searchableguy

# Description

fixes https://github.com/unlock-protocol/unlock/issues/9867

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

## Release Note Draft Snippet

2022-10-14 08:27 UTC, kalidiagne commented
need to add changelog and bump version for `unlock-js`

2022-10-14 09:32 UTC, kalidiagne approved these changes

2022-10-14 14:06 UTC, julien51 commented
Let's get @ChialiTsai 's feedback I'd design here please. I am not sure this yes the right approach.

2022-10-14 14:16 UTC, julien51 commented on unlock-app/src/components/interface/checkout/alpha/Checkout/Select.tsx
> +                                      Owned
I think it is a great idea to show to the user when they already have a membership to a lock, but I am not sure this UI is the right one :/

2022-10-14 14:17 UTC, julien51 commented on unlock-app/src/components/interface/checkout/alpha/Checkout/Select.tsx
> +                                    <Badge variant="primary" size="tiny">
I am not sure this is the right place to show this... and even if it is I don;t think this is the right UI.

I think confirmation is a much better place.

2022-10-14 14:18 UTC, julien51 requested changes
I would love @ChialiTsai 's comments on the best way to show these 2 elements:
* user already has a membership to the lock
* membership will renew.

2022-10-14 16:23 UTC, searchableguy commented
As mentioned - this is what we have in the figma design. Happy to make the changes once I get new design.

2022-10-14 20:30 UTC, ChialiTsai commented
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/16527634/195938086-35f01720-519a-4b3d-997d-e58de8b349d5.png">


May I propose the UI change to this? @searchableguy

2022-10-15 00:59 UTC, searchableguy commented
@julien51 is above good to implement?

2022-10-16 04:42 UTC, julien51 commented
Yes! That's much better imo

2022-10-17 19:31 UTC, searchableguy commented
<img width="550" alt="CleanShot 2022-10-18 at 00 56 15@2x" src="https://user-images.githubusercontent.com/73341821/196265881-064a8638-fb0f-45a3-a5d6-2269bd18e4c6.png">

2022-10-17 20:42 UTC, julien51 approved these changes

2022-10-18 09:44 UTC, merged